[package]
name = "node-rpc"
version = "3.0.0-dev"
authors.workspace = true
description = "Substrate node rpc methods."
edition.workspace = true
license = "Apache-2.0"
homepage = "https://substrate.io"
repository.workspace = true
publish = false

[lints]
workspace = true

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]

[dependencies]
jsonrpsee = { version = "0.22", features = ["server"] }
node-primitives = { git = "https://github.com/paritytech/polkadot-sdk.git", tag = "v1.9.0-rc1" }
pallet-transaction-payment-rpc = { git = "https://github.com/paritytech/polkadot-sdk.git", tag = "v1.9.0-rc1" }
mmr-rpc = { git = "https://github.com/paritytech/polkadot-sdk.git", tag = "v1.9.0-rc1" }
sc-chain-spec = { git = "https://github.com/paritytech/polkadot-sdk.git", tag = "v1.9.0-rc1" }
sc-client-api = { git = "https://github.com/paritytech/polkadot-sdk.git", tag = "v1.9.0-rc1" }
sc-consensus-babe = { git = "https://github.com/paritytech/polkadot-sdk.git", tag = "v1.9.0-rc1" }
sc-consensus-babe-rpc = { git = "https://github.com/paritytech/polkadot-sdk.git", tag = "v1.9.0-rc1" }
# sc-consensus-beefy = { git = "https://github.com/paritytech/polkadot-sdk.git", tag = "v1.9.0-rc1" }
sc-consensus-beefy = { path = "../../client/consensus/beefy" }
sc-consensus-beefy-rpc = { path = "../../client/consensus/beefy/rpc" }
# sc-consensus-beefy-rpc = { git = "https://github.com/paritytech/polkadot-sdk.git", tag = "v1.9.0-rc1" }
sc-consensus-grandpa = { git = "https://github.com/paritytech/polkadot-sdk.git", tag = "v1.9.0-rc1" }
sc-consensus-grandpa-rpc = { git = "https://github.com/paritytech/polkadot-sdk.git", tag = "v1.9.0-rc1" }
sc-mixnet = { git = "https://github.com/paritytech/polkadot-sdk.git", tag = "v1.9.0-rc1" }
sc-rpc = { git = "https://github.com/paritytech/polkadot-sdk.git", tag = "v1.9.0-rc1" }
sc-rpc-api = { git = "https://github.com/paritytech/polkadot-sdk.git", tag = "v1.9.0-rc1" }
sc-rpc-spec-v2 = { git = "https://github.com/paritytech/polkadot-sdk.git", tag = "v1.9.0-rc1" }
sc-sync-state-rpc = { git = "https://github.com/paritytech/polkadot-sdk.git", tag = "v1.9.0-rc1" }
sc-transaction-pool-api = { git = "https://github.com/paritytech/polkadot-sdk.git", tag = "v1.9.0-rc1" }
sp-api = { git = "https://github.com/paritytech/polkadot-sdk.git", tag = "v1.9.0-rc1" }
sp-block-builder = { git = "https://github.com/paritytech/polkadot-sdk.git", tag = "v1.9.0-rc1" }
sp-blockchain = { git = "https://github.com/paritytech/polkadot-sdk.git", tag = "v1.9.0-rc1" }
sp-consensus = { git = "https://github.com/paritytech/polkadot-sdk.git", tag = "v1.9.0-rc1" }
sp-consensus-babe = { git = "https://github.com/paritytech/polkadot-sdk.git", tag = "v1.9.0-rc1" }
sp-keystore = { git = "https://github.com/paritytech/polkadot-sdk.git", tag = "v1.9.0-rc1" }
sp-runtime = { git = "https://github.com/paritytech/polkadot-sdk.git", tag = "v1.9.0-rc1" }
sp-statement-store = { git = "https://github.com/paritytech/polkadot-sdk.git", tag = "v1.9.0-rc1" }
substrate-frame-rpc-system = { git = "https://github.com/paritytech/polkadot-sdk.git", tag = "v1.9.0-rc1" }
substrate-state-trie-migration-rpc = { git = "https://github.com/paritytech/polkadot-sdk.git", tag = "v1.9.0-rc1" }
