[package]
name = "node"
version = "4.0.0-dev"
description = "A fresh FRAME-based Substrate node, ready for hacking."
authors = ["Substrate DevHub <https://github.com/substrate-developer-hub>"]
homepage = "https://substrate.io/"
edition = "2021"
license = "MIT-0"
publish = false
repository = "https://github.com/ideal-lab5/etf"
build = "build.rs"

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]

[[bin]]
name = "node"

[dependencies]
array-bytes = "6.1.0"
clap = { version = "4.4.2", features = ["derive"] }
futures = { version = "0.3.21", features = ["thread-pool"]}
serde = { version = "1.0.188", default-features = false, features = ["derive", "alloc"] }
serde_json = "1.0.108"
thiserror = "1.0.48"
log = "0.4.17"
num-bigint = "0.4.4"

sc-cli = { git = "https://github.com/paritytech/polkadot-sdk.git", tag = "v1.4.0-rc1"  }
sp-core = { git = "https://github.com/paritytech/polkadot-sdk.git", tag = "v1.4.0-rc1"  }
sc-executor = { git = "https://github.com/paritytech/polkadot-sdk.git", tag = "v1.4.0-rc1"  }
sc-network = { git = "https://github.com/paritytech/polkadot-sdk.git", tag = "v1.4.0-rc1"  }
sc-service = { git = "https://github.com/paritytech/polkadot-sdk.git", tag = "v1.4.0-rc1"  }
sc-telemetry = { git = "https://github.com/paritytech/polkadot-sdk.git", tag = "v1.4.0-rc1"  }
sc-transaction-pool = { git = "https://github.com/paritytech/polkadot-sdk.git", tag = "v1.4.0-rc1"  }
sc-transaction-pool-api = { git = "https://github.com/paritytech/polkadot-sdk.git", tag = "v1.4.0-rc1"  }
sc-offchain = { git = "https://github.com/paritytech/polkadot-sdk.git", tag = "v1.4.0-rc1"  }
sc-statement-store = { git = "https://github.com/paritytech/polkadot-sdk.git", tag = "v1.4.0-rc1"  }
sc-consensus-etf-aura = { path = "../client/consensus/aura" }
sp-consensus-etf-aura = { path = "../primitives/consensus/aura" }

sc-consensus = { git = "https://github.com/paritytech/polkadot-sdk.git", tag = "v1.4.0-rc1"  }
sc-consensus-grandpa = { git = "https://github.com/paritytech/polkadot-sdk.git", tag = "v1.4.0-rc1"  }
sp-consensus-grandpa = { git = "https://github.com/paritytech/polkadot-sdk.git", tag = "v1.4.0-rc1"  }
sc-client-api = { git = "https://github.com/paritytech/polkadot-sdk.git", tag = "v1.4.0-rc1"  }
sp-runtime = { git = "https://github.com/paritytech/polkadot-sdk.git", tag = "v1.4.0-rc1"  }
sp-io = { git = "https://github.com/paritytech/polkadot-sdk.git", tag = "v1.4.0-rc1"  }
sp-timestamp = { git = "https://github.com/paritytech/polkadot-sdk.git", tag = "v1.4.0-rc1"  }
sp-inherents = { git = "https://github.com/paritytech/polkadot-sdk.git", tag = "v1.4.0-rc1"  }
sp-keyring = { git = "https://github.com/paritytech/polkadot-sdk.git", tag = "v1.4.0-rc1"  }
frame-system = { git = "https://github.com/paritytech/polkadot-sdk.git", tag = "v1.4.0-rc1"  }
pallet-transaction-payment = { default-features = false, git = "https://github.com/paritytech/polkadot-sdk.git", tag = "v1.4.0-rc1"  }

etf-crypto-primitives = { git = "https://github.com/ideal-lab5/etf-sdk/", branch = "dpss-noscale" }
paillier = { package="kzen-paillier", git = "https://github.com/ideal-lab5/rust-paillier", default-features = false }
rand_chacha = { version = "0.3.1" }
ark-bls12-381 = { version = "0.4.0", features = ["curve"]}
ark-ff = { version = "0.4.0"}
ark-serialize = { version = "0.4.0"}

# These dependencies are used for the node template's RPCs
jsonrpsee = { version = "0.16.2", features = ["server"] }
sp-api = { git = "https://github.com/paritytech/polkadot-sdk.git", tag = "v1.4.0-rc1"  }
sc-rpc-api = { git = "https://github.com/paritytech/polkadot-sdk.git", tag = "v1.4.0-rc1"  }
sp-blockchain = { git = "https://github.com/paritytech/polkadot-sdk.git", tag = "v1.4.0-rc1"  }
sp-block-builder = { git = "https://github.com/paritytech/polkadot-sdk.git", tag = "v1.4.0-rc1"  }
sc-basic-authorship = { git = "https://github.com/paritytech/polkadot-sdk.git", tag = "v1.4.0-rc1"  }
substrate-frame-rpc-system = { git = "https://github.com/paritytech/polkadot-sdk.git", tag = "v1.4.0-rc1"  }
pallet-transaction-payment-rpc = { git = "https://github.com/paritytech/polkadot-sdk.git", tag = "v1.4.0-rc1"  }

# These dependencies are used for runtime benchmarking
frame-benchmarking = { git = "https://github.com/paritytech/polkadot-sdk.git", tag = "v1.4.0-rc1"  }
frame-benchmarking-cli = { git = "https://github.com/paritytech/polkadot-sdk.git", tag = "v1.4.0-rc1"  }

# Local Dependencies
node-runtime = { version = "4.0.0-dev", path = "../runtime" }

# CLI-specific dependencies
try-runtime-cli = { optional = true, git = "https://github.com/paritytech/polkadot-sdk.git", tag = "v1.4.0-rc1"  }

[build-dependencies]
substrate-build-script-utils = { git = "https://github.com/paritytech/polkadot-sdk.git", tag = "v1.4.0-rc1"  }

[features]
default = []
# Dependencies that are only required if runtime benchmarking should be build.
runtime-benchmarks = [
	"node-runtime/runtime-benchmarks",
	"frame-benchmarking/runtime-benchmarks",
	"frame-benchmarking-cli/runtime-benchmarks",
]
# Enable features that allow the runtime to be tried and debugged. Name might be subject to change
# in the near future.
try-runtime = ["node-runtime/try-runtime", "try-runtime-cli/try-runtime"]