[package]
name = "node"
version = "4.0.0-dev"
description = "A fresh FRAME-based Substrate node, ready for hacking."
authors = ["Substrate DevHub <https://github.com/substrate-developer-hub>"]
homepage = "https://substrate.io/"
edition = "2021"
license = "MIT-0"
publish = false
repository = "https://github.com/ideal-lab5/etf"
build = "build.rs"

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]

[[bin]]
name = "node"

[dependencies]
log = { version = "0.4.17", default-features = false }
array-bytes = "6.1.0"
rand = "0.8.5"
codec = { package = "parity-scale-codec", version = "3.2.2", default-features = false, features = ["derive", "max-encoded-len"] }
clap = { version = "4.4.2", features = ["derive"] }
futures = { version = "0.3.21", features = ["thread-pool"]}
serde = { version = "1.0.188", default-features = false, features = ["derive", "alloc"] }
serde_json = "1.0.108"

sc-cli = { git = "https://github.com/paritytech/polkadot-sdk.git", tag = "v1.8.0-rc1"  }
sp-core = { git = "https://github.com/paritytech/polkadot-sdk.git", tag = "v1.8.0-rc1"  }
sc-executor = { git = "https://github.com/paritytech/polkadot-sdk.git", tag = "v1.8.0-rc1"  }
sc-network = { git = "https://github.com/paritytech/polkadot-sdk.git", tag = "v1.8.0-rc1"  }
sc-service = { git = "https://github.com/paritytech/polkadot-sdk.git", tag = "v1.8.0-rc1"  }
sc-telemetry = { git = "https://github.com/paritytech/polkadot-sdk.git", tag = "v1.8.0-rc1"  }
sc-transaction-pool = { git = "https://github.com/paritytech/polkadot-sdk.git", tag = "v1.8.0-rc1"  }
sc-transaction-pool-api = { git = "https://github.com/paritytech/polkadot-sdk.git", tag = "v1.8.0-rc1"  }
sc-offchain = { git = "https://github.com/paritytech/polkadot-sdk.git", tag = "v1.8.0-rc1"  }
sc-statement-store = { git = "https://github.com/paritytech/polkadot-sdk.git", tag = "v1.8.0-rc1"  }
sc-rpc = { git = "https://github.com/paritytech/polkadot-sdk.git", tag = "v1.8.0-rc1"  }

sc-consensus = { git = "https://github.com/paritytech/polkadot-sdk.git", tag = "v1.8.0-rc1"  }
sp-consensus = { git = "https://github.com/paritytech/polkadot-sdk.git", tag = "v1.8.0-rc1"  }
sp-keystore = { git = "https://github.com/paritytech/polkadot-sdk.git", tag = "v1.8.0-rc1"  }
mmr-rpc = { git = "https://github.com/paritytech/polkadot-sdk.git", tag = "v1.8.0-rc1"  }
mmr-gadget = { git = "https://github.com/paritytech/polkadot-sdk.git", tag = "v1.8.0-rc1"  }
beefy-primitives = { package = "sp-consensus-beefy", git = "https://github.com/paritytech/polkadot-sdk.git", tag = "v1.8.0-rc1"  }
grandpa-primitives = { package = "sp-consensus-grandpa", git = "https://github.com/paritytech/polkadot-sdk.git", tag = "v1.8.0-rc1"  }
sc-network-sync = { git = "https://github.com/paritytech/polkadot-sdk.git", tag = "v1.8.0-rc1"  }
sc-network-statement = { git = "https://github.com/paritytech/polkadot-sdk.git", tag = "v1.8.0-rc1"  }
sc-chain-spec = { git = "https://github.com/paritytech/polkadot-sdk.git", tag = "v1.8.0-rc1"  }
sc-sync-state-rpc = { git = "https://github.com/paritytech/polkadot-sdk.git", tag = "v1.8.0-rc1"  }
substrate-state-trie-migration-rpc = { git = "https://github.com/paritytech/polkadot-sdk.git", tag = "v1.8.0-rc1" }
frame-system-rpc-runtime-api = { git = "https://github.com/paritytech/polkadot-sdk.git", tag = "v1.8.0-rc1" }
sp-statement-store = { git = "https://github.com/paritytech/polkadot-sdk.git", tag = "v1.8.0-rc1"  }
sc-consensus-grandpa = { git = "https://github.com/paritytech/polkadot-sdk.git", tag = "v1.8.0-rc1"  }
sc-consensus-grandpa-rpc = { git = "https://github.com/paritytech/polkadot-sdk.git", tag = "v1.8.0-rc1"  }
sc-consensus-babe = { git = "https://github.com/paritytech/polkadot-sdk.git", tag = "v1.8.0-rc1"  }
sp-consensus-babe = { git = "https://github.com/paritytech/polkadot-sdk.git", tag = "v1.8.0-rc1"  }
sc-consensus-babe-rpc = { git = "https://github.com/paritytech/polkadot-sdk.git", tag = "v1.8.0-rc1"  }
beefy = { package = "sc-consensus-beefy", git = "https://github.com/paritytech/polkadot-sdk.git", tag = "v1.8.0-rc1"  }
sc-consensus-beefy-rpc = { git = "https://github.com/paritytech/polkadot-sdk.git", tag = "v1.8.0-rc1"  }
sc-authority-discovery = { git = "https://github.com/paritytech/polkadot-sdk.git", tag = "v1.8.0-rc1"  }
sp-authority-discovery = { git = "https://github.com/paritytech/polkadot-sdk.git", tag = "v1.8.0-rc1"  }
sc-mixnet = { git = "https://github.com/paritytech/polkadot-sdk.git", tag = "v1.8.0-rc1"  }
sp-mixnet = { git = "https://github.com/paritytech/polkadot-sdk.git", tag = "v1.8.0-rc1"  }
sc-consensus-slots = { git = "https://github.com/paritytech/polkadot-sdk.git", tag = "v1.8.0-rc1"  }
sc-rpc-spec-v2 = { git = "https://github.com/paritytech/polkadot-sdk.git", tag = "v1.8.0-rc1"  }
sc-client-api = { git = "https://github.com/paritytech/polkadot-sdk.git", tag = "v1.8.0-rc1"  }
sp-runtime = { git = "https://github.com/paritytech/polkadot-sdk.git", tag = "v1.8.0-rc1"  }
sp-io = { git = "https://github.com/paritytech/polkadot-sdk.git", tag = "v1.8.0-rc1"  }
sp-timestamp = { git = "https://github.com/paritytech/polkadot-sdk.git", tag = "v1.8.0-rc1"  }
sp-inherents = { git = "https://github.com/paritytech/polkadot-sdk.git", tag = "v1.8.0-rc1"  }
sp-keyring = { git = "https://github.com/paritytech/polkadot-sdk.git", tag = "v1.8.0-rc1"  }
frame-system = { git = "https://github.com/paritytech/polkadot-sdk.git", tag = "v1.8.0-rc1"  }
pallet-transaction-payment = { default-features = false, git = "https://github.com/paritytech/polkadot-sdk.git", tag = "v1.8.0-rc1"  }
pallet-im-online = { git = "https://github.com/paritytech/polkadot-sdk.git", tag = "v1.8.0-rc1"  }
sp-transaction-storage-proof = { git = "https://github.com/paritytech/polkadot-sdk.git", tag = "v1.8.0-rc1"  }
sc-storage-monitor = { git = "https://github.com/paritytech/polkadot-sdk.git", tag = "v1.8.0-rc1"  }
# These dependencies are used for the node template's RPCs
jsonrpsee = { version = "0.16.2", features = ["server"] }
sp-api = { git = "https://github.com/paritytech/polkadot-sdk.git", tag = "v1.8.0-rc1"  }
sc-rpc-api = { git = "https://github.com/paritytech/polkadot-sdk.git", tag = "v1.8.0-rc1"  }
sp-blockchain = { git = "https://github.com/paritytech/polkadot-sdk.git", tag = "v1.8.0-rc1"  }
sp-block-builder = { git = "https://github.com/paritytech/polkadot-sdk.git", tag = "v1.8.0-rc1"  }
sc-basic-authorship = { git = "https://github.com/paritytech/polkadot-sdk.git", tag = "v1.8.0-rc1"  }
substrate-frame-rpc-system = { git = "https://github.com/paritytech/polkadot-sdk.git", tag = "v1.8.0-rc1"  }
pallet-transaction-payment-rpc = { git = "https://github.com/paritytech/polkadot-sdk.git", tag = "v1.8.0-rc1"  }

# These dependencies are used for runtime benchmarking
frame-benchmarking = { git = "https://github.com/paritytech/polkadot-sdk.git", tag = "v1.8.0-rc1"  }
frame-benchmarking-cli = { git = "https://github.com/paritytech/polkadot-sdk.git", tag = "v1.8.0-rc1"  }

# Local Dependencies
node-runtime = { version = "4.0.0-dev", path = "../runtime" }
node-primitives = { path = "../node-primitives" } 
# CLI-specific dependencies
try-runtime-cli = { optional = true, git = "https://github.com/paritytech/polkadot-sdk.git", tag = "v1.8.0-rc1"  }

[build-dependencies]
substrate-build-script-utils = { git = "https://github.com/paritytech/polkadot-sdk.git", tag = "v1.8.0-rc1"  }

[features]
default = []
# Dependencies that are only required if runtime benchmarking should be build.
runtime-benchmarks = [
	"node-runtime/runtime-benchmarks",
	"frame-benchmarking/runtime-benchmarks",
	"frame-benchmarking-cli/runtime-benchmarks",
]
# Enable features that allow the runtime to be tried and debugged. Name might be subject to change
# in the near future.
try-runtime = ["node-runtime/try-runtime", "try-runtime-cli/try-runtime"]
